SELECT MAX(price) AS max_price FROM INGREDIENT WHERE calories > 500;
SELECT AVG(calories) AS avg_calories FROM INGREDIENT WHERE price > 15;
SELECT * FROM INGREDIENT HAVING price = (SELECT MAX(price) FROM INGREDIENT);
SELECT * FROM INGREDIENT HAVING price < (SELECT AVG(price) FROM INGREDIENT);
SELECT * FROM INGREDIENT HAVING price < (SELECT AVG(price) FROM INGREDIENT) AND calories > 600;
